root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  include_ext = ["go", "toml", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500

[log]
  main_only = false
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
